#!/usr/bin/env python3
from subprocess import run, PIPE
import re
battfile="/org/freedesktop/UPower/devices/battery_C23B"
batstat = run(f"upower -i {battfile}",stdout=PIPE,shell=True)
percstr = ""
for line in batstat.stdout.decode().split("\n"):
    if "state" in line:
        stateline = line
    if "percentage" in line:
        percstr=line
state = re.sub(r"\s*state:\s*", '', stateline)
perc=re.search(r"\d\d\d?%",percstr)
percent = percstr[perc.start():perc.end()].strip('%')
if state == "fully-charged":
    print(state)
    print(state)
else:
    print(state, '-', percent + '%')
    print(state, '-', percent + '%')

if int(percent) > 90:
    print("#22FF22")
elif int(percent) > 75:
    print("#55FF22")
elif int(percent) > 60:
    print("#AAFF00")
elif int(percent) > 40:
    print("#FFFF00")
elif int(percent) > 25:
    print("#FF8822")
else:
    print("#FF2222")
